### ISSUE TITLE
Parser rule for namespaced maps

### ISSUE THREAD

**Issue by trptcolin** [cgrand/sjacket#25]
As reported by https://github.com/technomancy/leiningen/issues/2310, namespaced maps don't parse yet. I took a quick crack at it, something like 

```clojure
   :namespaced-map ["#"
                    (re/regex (re/repeat ":" 1 2))
                    #{"" :symbol}
                    :map]

```

but that's not quite right (`Ambiguous match` for sets), so there's more thinking to do. Some ideas for test cases: https://github.com/clojure/clojure/blob/e19157c4809622fcaac1d8ccca8e3f6a67b3d848/test/clojure/test_clojure/reader.cljc#L719-L747

**Comment by heptahedron** [comment]
I'm not experienced with any of this code, but from what I've read it looks like what you proposed didn't work because it would allow "#:{}", assuming the parser DSL uses vectors for sequencing and sets for disjunction.

Without yet knowing quite how to test this, I'd try something like

```clojure
:namespaced-map ["#" #{["::" #{"" :symbol}][":" :symbol]} map]
```

**Comment by heptahedron** [comment]
I've toyed with it for a while now, included `:` in the `dispatch-macro-char`s and I still can't get it to disambiguate.

```clojure
   :namespaced-map #{["#::{" :sexpr* "}"]
                     ["#::" :symbol "{" :sexpr* "}"]}
```

If only the first of the two options is included, then it will correctly return a `namespaced-map`, but the minute the next one is included it falls apart. I recognize the `"{" :sexpr* "}"` is the exact same as the definition for `:map` but I was getting desperate.
